### ISSUE TITLE
Temas a revisar en los Estatutos y en el Reglamento de Régimen Interno

### ISSUE THREAD

**Issue by dukebody** [python-spain/documentacion#25]
Migrado desde http://documentos-asociacion.es.python.org/revisi%C3%B3n%20de%20estatutos%20y%20rri.html.

* Añadir las entradas nuevas en orden inverso.
* Documentar los temas discutidos y resueltos, en un sentido u otro.

# Estatutos

* 20130225: Artículo 21: Clarificar si una Junta con quorum, pero dividida en una votación, puede tomar decisiones vinculantes. Discutido en la lista de Junta.

# Reglamento de Régimen Interno

* 20130306: Las reuniones de la Junta Directiva que se celebren usando medios de comunicación a distancia, habrán de convocarse con una antelación mínima de 72 horas.
* 20130306: Pendiente fijar antelación mínima para convocar reuniones presenciales.

***
¿Cómo de necesario es resolver esto? @maigimenez

**Comment by maigimenez** [comment]
Ufff esa documentación es tan antigua que no tengo claro a qué se refería. Todas las actas están en aquí, tanto las antiguas como las nuevas. 
Feliz de ayudar si tienes algo más de información que me pueda guiar.

**Comment by dukebody** [comment]
Si tú no sabes a qué se refiere esto, los cambios propuestos no se han accionado en absoluto y son super antiguos, probablemente es que no sean importantes, así que yo daría estos "temas a revisar" por finiquitados. @Juanlu001 ?

**Comment by maigimenez** [comment]
Si, yo entiendo que esos "temas a revisar" se debieron ser revisados y ya no son importantes. 
En esta junta es raro los votos muy divididos pero siempre quedan en el acta las opiniones personales de cada miembro de la junta. Las decisiones vinculantes siempre han tenido el apoyo de todas las personas de la junta, que yo recuerde.

**Comment by astrojuanlu** [comment]
> Si tú no sabes a qué se refiere esto, los cambios propuestos no se han accionado en absoluto y son super antiguos, probablemente es que no sean importantes, así que yo daría estos "temas a revisar" por finiquitados.

Finiquitados.
