### ISSUE TITLE
Lenguaje inclusivo en Estatutos

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/documentacion#28]
Me he encontrado con esto (énfasis mío):

> Convocada Asamblea General para la designación de la Junta Directiva, los socios que pretendan ejercer su derecho de elegibilidad, habrán de presentar su candidatura (que constará, al menos, de **Presidente, Vicepresidente, Secretario y Tesorero**)

No he hecho una revisión exhaustiva de todas nuestras normas internas, pero en este caso concreto creo que sería tan fácil como cambiar eso por "Presidencia, Vicepresidencia, Secretaría y Tesorería".

Sé que cambiar los Estatutos lleva tiempo, y por eso precisamente cuanto antes lo planteemos, mejor (aunque tengamos que esperar a 2021 para realmente conseguirlo). ¿Opiniones?

**Comment by dukebody** [comment]
Finiquitado!
